Enabled-Modules:
  - Admin
  - Afk
  - BetterPistons
  - Builder
  - CaptureBall
  - ChatChannels
  - ChunkLoader
  - Crafting
  - EnderPearlTeleport
  - GoldTool
  - InkSign
  - Invite
  - JetBoot
  - MiningWorld
  - MobTurret
  - Rail
  - Shop
  - Stargate
  - InfiniteCarts
  - InfiniteSigns
  - DisableExplosions
  - EnderEyeChests
Disabled-Commands:
  - mod
Spawn-Location: ""
Default-Group: "default"
Mod-Group: "mod"
Chat-Color: true
Module-Settings:
  Afk-Module:
    Afk-Time-Seconds: 300
  Builder-Module:
    RotatorTool-Material: BLAZE_ROD
  CaptureBall-Module:
    Banned-Mobs:
      - ARMOR_STAND
      - ENDER_DRAGON
      - SHULKER
      - WANDERING_TRADER
      - TRADER_LLAMA
      - WITHER
      - VILLAGER
      - ZOMBIE_VILLAGER
  ChatChannels-Module:
    Chat-Format: '&a[%channel%] %player%: %message%'
    Global-Chat-Format: '<%playerDisplay%> %message%'
    Leave-Format: '&e[%channel%] User %player% has left the channel.'
    Join-Format: '&e[%channel%] User %player% has joined the channel.'
  Stargate-Module:
    Portal-Reset-Time: 4
  JetBoot-Module:
    JetBoot-Damage: 1
    Durability-Update-Freq: 10
    Ignore-Unbreaking: false
    Tiers:
      Tier-One-Radius: 20
      Tier-Two-Radius: 30
      Tier-Three-Radius: 40
      Tier-Four-Radius: 50
    Multipliers:
      Iron-Multiplier: 1
      Gold-Multiplier: 1.2
      Diamond-Multiplier: 1.4
      Emerald-Multiplier: 1.6
      Netherite-Multiplier: 1.8
  InkSign-Module:
    Tool-Material: INK_SAC
  MobTurret-Module:
    Turret-Radius: 45
    Turret-Attack-Damage: 10
    Turret-Attack-Interval: 10
    Attackable-Mobs:
      - BLAZE
      - CAVE_SPIDER
      - CREEPER
      - DROWNED
      - EVOKER
      - ENDERMAN
      - GHAST
      - GUARDIAN
      - HUSK
      - ILLUSIONER
      - MAGMA_CUBE
      - PHANTOM
      - PILLAGER
      - RAVAGER
      - SILVERFISH
      - SKELETON
      - SLIME
      - SPIDER
      - VEX
      - VINDICATOR
      - WITCH
      - WITHER_SKELETON
      - ZOMBIE
      - ZOMBIE_VILLAGER
  MiningWorld-Module:
    World-Reset-Period: '0 0 2 ? * FRI'