Enabled-Modules:
  - Admin
  - BetterPistons
  - CaptureBall
  - ChatChannels
  - ChunkLoader
  - Crafting
  - EnderPearlTeleport
  - Galapagos
  - GoldTool
  - InkSign
  - Invite
  - JetBoot
  - MiningWorld
  - MobTurret
  - Rail
  - Rotator
  - Shop
  - Stargate
  - InfiniteCarts
  - InfiniteSigns
  - DisableExplosions
  - EnderEyeChests
Disabled-Commands:
  - mod
Spawn-Location: ""
Default-Group: "default"
Mod-Group: "mod"
Chat-Color: true
Module-Settings:
  Stargate-Module:
    Portal-Reset-Time: 4
  JetBoot-Module:
    JetBoot-Damage: 1
    Durability-Update-Freq: 10
    Tier-One-Radius: 20
    Tier-Two-Radius: 30
    Tier-Three-Radius: 40
    Tier-Four-Radius: 50
  Rotator-Module:
    Tool-Material: 'BLAZE_ROD'
  InkSign-Module:
    Tool-Material: 'INK_SAC'
  Galapagos-Module:
    #Percent chance of spawning
    Spawn-Chance: 5
  ChatChannels-Module:
    Chat-Format: '&a[%channel%] %player%: %message%'
    Global-Chat-Format: '<%playerDisplay%> %message%'
    Leave-Format: '&e[%channel%] User %player% has left the channel.'
    Join-Format: '&e[%channel%] User %player% has joined the channel.'
  MobTurret-Module:
    Turret-Radius: 45
  CaptureBall-Module:
    Banned-Mobs:
      - ARMOR_STAND
      - ENDER_DRAGON
      - PLAYER
      - SHULKER
      - WANDERING_TRADER
      - TRADER_LLAMA
      - WITHER
      - VILLAGER
      - ZOMBIE_VILLAGER
  ProgressiveDeepslate-Module:

    Usable-Picks:
      - DIAMOND_PICKAXE
      - NETHERITE_PICKAXE