main: com.ryanjhuston.SkcraftBasics
name: SkcraftBasics
version: 1.0
api-version: 1.14
commands:
  accept:
    description: Accept teleport requests from player.
  paccept:
    description: Permanently accept teleport requests from player.
  invite:
    description: Invite players to server.
  setspawn:
    description: Change spawn location.
  nethercoords:
    description: Get needed portal location in other world.
  here:
    description: List players in current chat channel.
  join:
    description: Join chat channel.
  leave:
    description: Leave chat channel.
  g:
    description: Message global chat when in a channel.
  help:
    description: A not very helpful help command.
  worldmanager:
    description: A world management addition.
  wm:
    description: Short form of /worldmanager.
  admin:
    description: Admin creation command