main: com.ryanjhuston.SkcraftBasics
name: SkcraftBasics
version: 1.0
api-version: 1.14
commands:
  accept:
    description: Accept teleport requests from player.
  invite:
    description: Invite players to server.
  setspawn:
    description: Change spawn location.