main: com.ryanjhuston.SkcraftBasics
name: SkcraftBasics
version: 1.0.1
api-version: 1.15
commands:
  accept:
    description: Accept teleport requests from player.
  paccept:
    description: Permanently accept teleport requests from player.
  invite:
    description: Invite players to server.
  nethercoords:
    description: Get needed portal location in other world.
  here:
    description: List players in current chat channel.
  join:
    description: Join chat channel.
  leave:
    description: Leave chat channel.
  worldmanager:
    description: A world management addition.
  wm:
    description: Short form of /worldmanager.
  sb:
    description: SkcraftBasics command.
  sba:
      description: SkcraftBasics admin command.